window.APP_DATA = window.APP_DATA || {};
window.APP_DATA.reservations = [
  {
    reservation_id: "R0001",
    room_name: "委員会室",
    reservation_date: "2026-04-07",
    time_slot: "AM",
    start_time: "09:00",
    end_time: "10:00",
    purpose: "総務部会議",
    department_name: "総務課",
    person_in_charge: "山田太郎",
    entered_by: "事務局A",
    status: "承認済",
    display_order: 1,
    note: "",
    created_at: "2026-04-01",
    updated_at: "2026-04-01"
  },
  {
    reservation_id: "R0002",
    room_name: "委員会室",
    reservation_date: "2026-04-07",
    time_slot: "AM",
    start_time: "10:30",
    end_time: "11:30",
    purpose: "打合せ",
    department_name: "財政課",
    person_in_charge: "佐藤次郎",
    entered_by: "事務局B",
    status: "承認済",
    display_order: 2,
    note: "資料持参",
    created_at: "2026-04-01",
    updated_at: "2026-04-01"
  },
  {
    reservation_id: "R0003",
    room_name: "委員会室",
    reservation_date: "2026-04-07",
    time_slot: "PM",
    start_time: "",
    end_time: "",
    purpose: "住民説明会",
    department_name: "市民課",
    person_in_charge: "鈴木一郎",
    entered_by: "事務局A",
    status: "申請中",
    display_order: 1,
    note: "外部参加あり",
    created_at: "2026-04-02",
    updated_at: "2026-04-02"
  },
  {
    reservation_id: "R0004",
    room_name: "小委員会室",
    reservation_date: "2026-04-07",
    time_slot: "PM",
    start_time: "13:00",
    end_time: "14:00",
    purpose: "小委員会打合せ",
    department_name: "総務課",
    person_in_charge: "山田太郎",
    entered_by: "事務局A",
    status: "承認済",
    display_order: 1,
    note: "",
    created_at: "2026-04-02",
    updated_at: "2026-04-02"
  },
  {
    reservation_id: "R0005",
    room_name: "部課長控室",
    reservation_date: "2026-04-08",
    time_slot: "PM",
    start_time: "14:00",
    end_time: "15:00",
    purpose: "部長協議",
    department_name: "企画課",
    person_in_charge: "高橋健",
    entered_by: "事務局B",
    status: "承認済",
    display_order: 1,
    note: "",
    created_at: "2026-04-03",
    updated_at: "2026-04-03"
  },
  {
    reservation_id: "R0006",
    room_name: "小会議室",
    reservation_date: "2026-04-08",
    time_slot: "AM",
    start_time: "09:30",
    end_time: "10:30",
    purpose: "面談",
    department_name: "人事課",
    person_in_charge: "加藤翔",
    entered_by: "事務局A",
    status: "承認済",
    display_order: 1,
    note: "来客対応",
    created_at: "2026-04-03",
    updated_at: "2026-04-03"
  },
  {
    reservation_id: "R0007",
    room_name: "委員会室",
    reservation_date: "2026-04-09",
    time_slot: "AM",
    start_time: "",
    end_time: "",
    purpose: "定例会準備",
    department_name: "議事課",
    person_in_charge: "事務局C",
    entered_by: "事務局C",
    status: "承認済",
    display_order: 1,
    note: "",
    created_at: "2026-04-04",
    updated_at: "2026-04-04"
  },
  {
    reservation_id: "R0008",
    room_name: "委員会室",
    reservation_date: "2026-04-09",
    time_slot: "PM",
    start_time: "",
    end_time: "",
    purpose: "定例会準備",
    department_name: "議事課",
    person_in_charge: "事務局C",
    entered_by: "事務局C",
    status: "承認済",
    display_order: 1,
    note: "",
    created_at: "2026-04-04",
    updated_at: "2026-04-04"
  },
  {
    reservation_id: "R0009",
    room_name: "小会議室",
    reservation_date: "2026-04-09",
    time_slot: "PM",
    start_time: "15:00",
    end_time: "16:00",
    purpose: "面談",
    department_name: "福祉課",
    person_in_charge: "高橋健",
    entered_by: "事務局A",
    status: "キャンセル",
    display_order: 1,
    note: "利用者都合",
    created_at: "2026-04-05",
    updated_at: "2026-04-05"
  },
  {
    reservation_id: "R0010",
    room_name: "部課長控室",
    reservation_date: "2026-04-10",
    time_slot: "AM",
    start_time: "09:00",
    end_time: "10:00",
    purpose: "課長会",
    department_name: "企画課",
    person_in_charge: "佐藤次郎",
    entered_by: "事務局B",
    status: "承認済",
    display_order: 1,
    note: "",
    created_at: "2026-04-06",
    updated_at: "2026-04-06"
  },
  {
    reservation_id: "R0011",
    room_name: "小会議室",
    reservation_date: "2026-04-10",
    time_slot: "PM",
    start_time: "",
    end_time: "",
    purpose: "資料確認",
    department_name: "総務課",
    person_in_charge: "山田太郎",
    entered_by: "事務局A",
    status: "承認済",
    display_order: 1,
    note: "",
    created_at: "2026-04-06",
    updated_at: "2026-04-06"
  },
  {
    reservation_id: "R0012",
    room_name: "小委員会室",
    reservation_date: "2026-04-10",
    time_slot: "AM",
    start_time: "10:00",
    end_time: "11:00",
    purpose: "打合せ",
    department_name: "財政課",
    person_in_charge: "鈴木一郎",
    entered_by: "事務局B",
    status: "却下",
    display_order: 1,
    note: "時間重複",
    created_at: "2026-04-06",
    updated_at: "2026-04-07"
  }
];